/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */


using System;
using UnityEngine;


namespace AndroidNativeCore
{
    public class AlertDialog  {

        public delegate void dialogOnClick();
        private delegate void onClick(String id);

        private static event onClick onClickHandler;
   
        public const int THEME_TRADITIONAL = 1;
        public const int THEME_HOLO_DARK = 2;
        public const int THEME_HOLO_LIGHT = 3;
        public const int THEME_DEVICE_DEFAULT_LIGHT = 4;
        public const int THEME_DEVICE_DEFAULT_DARK = 5;

        private const string btn_negetive_id = "1";
        private const string btn_positive_id = "2";
        private const string btn_neutral_id = "3";

        private AndroidJavaObject Alert;


        public AlertDialog()
        {
            Alert = new AndroidJavaObject(AndroidCore.PluginPackage + ".Dialogs");
        }

        public AlertDialog build(int Theme)
        {
            Alert.Call("AlertBuild", Theme,new onClickListner());           
            return this;
        }
        public AlertDialog setTitle(string tit)
        {
            Alert.Call("AlertSetTitle",tit);
            return this;
        }
        public AlertDialog setIcon(string resourceId)
        {
            Alert.Call("AlertSetIcon", resourceId);
            return this;
        }
        public AlertDialog setMessage(string message)
        {
            Alert.Call("AlertSetMsg", message);
            return this;
        }
        public AlertDialog setPositiveButtion(string text,dialogOnClick onClick )
        {
            Alert.Call("AlertSetPositiveButtion", text,btn_positive_id);
            onClick a = null;
            a = (string id) =>
            {
                if(onClick != null)
                {
                    if (id.Equals(btn_positive_id)) { onClick.Invoke(); }                      
                }
                onClickHandler -= a;
            };
            onClickHandler += a;                  
            return this;
        }
        public AlertDialog setNegativeButtion(string text,dialogOnClick onClick)
        {
            Alert.Call("AlertSetNegtiveButtion", text,btn_negetive_id);
            onClick a = null;
            a = (string id) =>
            {
                if (onClick != null)
                {
                    if (id.Equals(btn_negetive_id)) { onClick.Invoke(); }
                }
                onClickHandler -= a;
            };
            onClickHandler += a;
            return this;
    }
        public AlertDialog setNeutralButtion(string text,dialogOnClick onClick)
        {
            Alert.Call("AlertSetNegtiveButtion", text, btn_neutral_id);
            onClick a = null;
            a = (string id) =>
            {
                if (onClick != null)
                {
                    if (id.Equals(btn_neutral_id)) { onClick.Invoke(); }
                }
                onClickHandler -= a;
            };
            onClickHandler += a;
            return this;
        }
        public void show()
        {
            Alert.Call("ShowAlert");
        }
        public void dismiss()
        {
            Alert.Call("dismissAlert");
        }

        private class onClickListner : AndroidJavaProxy
        {
            public onClickListner(): base(AndroidCore.PluginPackage+ ".callbacks.callBacks$onClickListener") { }
            void onClick(string id)
            {
                onClickHandler.Invoke(id);
            }
        }
    }
}
 

