/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AndroidNativeCore
{
    public class androidEventHandler : MonoBehaviour {

        public delegate void onImagePickHandler(string path);
        public delegate void onImageCansel();

        public static event onImagePickHandler onImagePickListner;
        public static event onImageCansel onImageCancelledListner;

        public AndroidJavaObject plugin;

        public AndroidJavaObject AndroidNativeCore()
        {
            return plugin;
        }

        // Events
        public void onImagePick(string path)
        {
            if(onImagePickListner != null)
            {
                onImagePickListner.Invoke(path);
            }
        }

        public void onCansel(string s)
        {
            if(onImageCancelledListner != null)
            {
                onImageCancelledListner.Invoke();
            }
           
        }
    }
}

