/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AndroidNativeCore
{
    public class Notification{

        public const int PRIORITY_DEFAULT = 0x00000000;
        public const int PRIORITY_HIGH = 0x00000001;
        public const uint PRIORITY_LOW = 0xffffffff;
        public const int PRIORITY_MAX = 0x00000002;
        public const uint PRIORITY_MIN = 0xfffffffe;

        private string img_url = "null";

        private AndroidJavaObject obj;


        public Notification()
        {
            obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
        }
        public Notification Create(string chanel)
        {
            obj.Call("NotificationBuilder", chanel);     
            return this;
        }
        public Notification setIcon(string resourseName)
        {
            obj.Call("NotificationSetIcon", resourseName);
            return this;
        }
        public Notification setDefautlSound()
        {
            obj.Call("NotificationSetDefaultSound");
            return this;
        }
        public Notification setContentTitle(string title)
        {
            obj.Call("NotificationSetTitle", title);
            return this;    
        }
        public Notification setBigText(string text)
        {
            obj.Call("NotificationSetMsg", text);
            return this;
        }
        public Notification setContentText(string text)
        {
            obj.Call("NotificationBigMsg", text);

            return this;
            
        }
        public Notification setBigImage(Texture2D largeicon)
        {
            byte[] data = largeicon.EncodeToPNG();
            obj.Call("NotificationSetLargeIcon", data);
            return this;              
        }
        public Notification setBigImage(string url)
        {
            this.img_url = url;
            return this;       
        }
        public Notification setSound(string resourceId)
        {
            obj.Call("NotificationSetSound", resourceId);
            return this;
        }
        public Notification setPriority(int priority)
        {
            obj.Call("NotificationSetPriority", priority);
            return this;
        }
        public Notification setGroup(string groupName,bool showGroupSummery)
        {
            obj.Call("NotificationsetGroup", groupName, showGroupSummery);
            return this;
        }
        public void notify(int id)
        {
            obj.Call("ShowNotification",id,img_url);
        }

        public class Channel
        {
            public const int IMPORTANCE_DEFAULT = 0x00000003;
            public const int IMPORTANCE_HIGH = 0x00000004;
            public const int IMPORTANCE_LOW = 0x00000002;
            public const int IMPORTANCE_MAX = 0x00000005;
            public const int IMPORTANCE_MIN = 0x00000001;
            public const int IMPORTANCE_NONE = 0x00000000;

            public const int VISIBILITY_PRIVATE = 0x00000000;
            public const int VISIBILITY_PUBLIC = 0x00000001;
            public const uint VISIBILITY_SECRET = 0xffffffff;

            private AndroidJavaObject notifi;
            public Channel()
            {
                notifi = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            }
            public void CreateChannel(string id,string name,string description,int importence,int lockScreenVisibility,bool enableLights,string lightColor,bool enableVibration,bool enableBadge)
            {
                notifi.Call("crateNotificationChanel", id, name, description, importence, lockScreenVisibility, enableLights, lightColor, enableVibration, enableBadge);
            }
            public void deleteChannel(string name)
            {
                notifi.Call("deleteNotificationChanel", name);
            }
        }
    }
}
 



