/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AndroidNativeCore
{
    public  class Toast {

        public const int LENGTH_SHORT = 6;
        public const int LENGTH_LONG = 7;

        public static void make(string text, int duration)
        {
            AndroidJavaClass toast = new AndroidJavaClass("android.widget.Toast");
            if(duration == LENGTH_SHORT)
            {
              AndroidJavaObject show = toast.CallStatic<AndroidJavaObject>("makeText", AndroidCore.getContext(), text, toast.GetStatic<int>("LENGTH_SHORT"));
                show.Call("show");
            }else if( duration == LENGTH_LONG)
            {
               AndroidJavaObject show = toast.CallStatic<AndroidJavaObject>("makeText", AndroidCore.getContext(), text, toast.GetStatic<int>("LENGTH_LONG"));
               show.Call("show");
            }     
        }
    }
}

