/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using UnityEngine;
using System.Collections;

namespace AndroidNativeCore
{
    public class Vibrator {

        public static void Vibrate(long milliseconds)
        {
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            obj.Call("Vibrate", milliseconds);
      
        }
        public static void Vibrate(long[] pattren, int repet)
        {                       
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            obj.Call("VibrateWaveForm", pattren, repet);          
        }
        public static void Cansel()
        {
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            obj.Call("VibrateCansel");
        }
    }
}

